### ISSUE TITLE
Use properly FIELDPRESS_SCRIPT_PREFIX 

### ISSUE THREAD

**Issue by codersantosh** [addonspress/fieldpress#6]
fieldpress.php line 30 
`defined('FIELDPRESS_SCRIPT_PREFIX') or define('FIELDPRESS_SCRIPT_PREFIX', ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min' );`
and use on `fieldpress_enqueue_scripts` function

**Comment by addonspress** [comment]
Fixed on 56ba202
